### ISSUE TITLE
when i install project, throw "invalid version: unknown revision c44533fe44bd"

### ISSUE THREAD

**Issue by ruqinhu** [trpc-group/trpc-go#104]
PS D:\code\gocode\trpc-go-r1.0\examples\helloworld\server> go install
go: downloading trpc.group/trpc/trpc-protocol/pb/go/trpc v0.1.2-0.20230530025122-c44533fe44bd
..\..\..\errs\errs.go:15:2: trpc.group/trpc/trpc-protocol/pb/go/trpc@v0.1.2-0.20230530025122-c44533fe44bd: invalid version: unknown revision c44533fe44bd

**Comment by WineChord** [comment]
Please provide a detailed description of all your steps, as the information provided so far is not sufficient.

**Comment by tocrafty** [comment]
This [`go.mod`](https://github.com/trpc-group/trpc-go/blob/main/examples/go.mod) is not correctly updated when open source.

**Comment by WineChord** [comment]
@ruqinhu fetch the latest commit of main branch and try again
