### ISSUE TITLE
Retry Hedging chinese doc link is not right

### ISSUE THREAD

**Issue by S1mpIe** [trpc-group/trpc-go#107]
https://github.com/trpc-group/trpc-go/blob/3582785c31d73a06be1c6b8db7bb8531909b60f8/docs/README.zh_CN.md?plain=1#L19

may be this link is right ?
https://github.com/trpc-ecosystem/go-filter/blob/main/slime/README_zh_CN.md

is README_zh_CN, not README.zh_CN

**Comment by tocrafty** [comment]
`README_zh_CN.md` should be renamed to `README.zh_CN.md`. I will fix it later.

**Comment by S1mpIe** [comment]
thanks for your reply :)
