### ISSUE TITLE
unable to access 'https://github.com/trpc-group/trpc/'

### ISSUE THREAD

**Issue by groupsell** [trpc-group/trpc-go#116]
resolve url: [trpc.group/trpc/trpc-protocol/pb/go/trpc v0.1.2-0.20230530025122-c44533fe44bd] failed, module not found
unable to access 'https://github.com/trpc-group/trpc/'

**Comment by WineChord** [comment]
possible duplicates: https://github.com/trpc-group/trpc-go/issues/104

git pull the latest commit of main branch

**Comment by sandyskies** [comment]
https://github.com/trpc-group/trpc-go/releases/tag/v1.0.1 use this tag
