### ISSUE TITLE
unreachable trpc.group/trpc-go/go_reuseport package

### ISSUE THREAD

**Issue by jackylong1** [trpc-group/trpc-go#117]
i clone the latest version of trpc-go
my system is darwin  arm64 

when i cd example to run hello as the doc say. i got the error as follow:
unrecognized import path "trpc.group/trpc-go/go_reuseport": https fetch: Get "https://trpc.group/trpc-go/go_reuseport?go-get=1":

**Comment by WineChord** [comment]
git pull the latest commit of trpc-go, not the latest tag/release.

**Comment by WineChord** [comment]
We are going to release a new version to address this issue.

**Comment by WineChord** [comment]
https://github.com/trpc-group/trpc-go/pull/118

**Comment by sandyskies** [comment]
https://github.com/trpc-group/trpc-go/releases/tag/v1.0.1 now u can use this tag
