### ISSUE TITLE
Congratulation! Should I submit the PR directly here or go to Tencent's internal GIT repository?

### ISSUE THREAD

**Issue by morrisxyang** [trpc-group/trpc-go#123]
Additionally, are there two versions coexisting?

**Comment by WineChord** [comment]
Perhaps the process involves first performing the internal merge request, and once those are completed, the changes are merged and then cherry-picked to GitHub.

**Comment by LinuxSuRen** [comment]
I'm wondering if having both internal and external git repositories is a normal situation in Tencent.

**Comment by liuzengh** [comment]
Depending on the actual situation of the project. There are some possible reasons why there are two versions, internal and open source:

- The company may require customized features or specific business needs that are not applicable to the open-source version.
- The company's internal code may contain some trade secrets or sensitive information, which cannot be fully disclosed to the open-source community.
- The company's internal code may use some third-party libraries or tools, and the use of these libraries or tools may be subject to different licenses or restrictions, so they cannot be fully disclosed to the open-source community.
- The company's internal code may use some proprietary technologies or algorithms that cannot be fully disclosed to the open-source community.

For tRPC project:  

1. At present, there are still a large number of users internally, and it is almost impossible not to maintain or promote the migration of the open-source version. In the long run, we hope to maintain only one version, most likely based on the open-source version (no specific deadline yet).
2. Currently, we synchronize cherry-pick for bugs and features internally and externally to ensure consistency as much as possible.  
3. In the short term, internal and external tags are managed separately.

**Comment by LinuxSuRen** [comment]
hi @liuzengh , thanks for the clarification. In my personal view, this is mostly an internal management issue. It could be a good open-source project if there is good communication between maintainers and contributors.

**Comment by itcyy** [comment]
Thank you to Tencent for opening up this framework, which allows developers to have more choices.
