### ISSUE TITLE
没看到tracing的实现代码，我看首页的架构图里有这个

### ISSUE THREAD

**Issue by Lowpower** [trpc-group/trpc-go#132]
### Preliminary Research

- [ ] I have read the project's documentation.
- [ ] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

**Comment by liuzengh** [comment]
The tracing plugin that has already been open-sourced: 

- https://github.com/trpc-ecosystem/go-opentracing-jaeger
- https://github.com/trpc-ecosystem/go-opentracing-zipkin
- https://github.com/trpc-ecosystem/go-opentracing-zipkin

The tracing plugin that will soon be open-sourced: *go-opentelementry*

Tracing within the trpc framework:  [rpcz](https://github.com/trpc-group/trpc-go/tree/main/rpcz), further reading: [origin-of-rpcz-name](https://github.com/trpc-group/trpc-go/tree/main/rpcz#origin-of-rpcz-name)

**Comment by Leoyoungxh** [comment]
Tracing plugins are implemented through the [filter](https://github.com/trpc-group/trpc-go/tree/main/filter) mechanism. You can find these tracing plugins in:
https://github.com/trpc-ecosystem/go-opentracing-skywalking
https://github.com/trpc-ecosystem/go-opentracing-jaeger
