### ISSUE TITLE
the repository URL on GitHub and the module definition in go.mod are not consistent

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-go#136]
trpc-go repo url path is github/trpc-group/trpc-go/trpc-go,but the go.mod module name is trpc.group/trpc-go/trpc-go

**Comment by zanlichard** [comment]
ping trpc.group
PING ins-q44ux95n.ias.tencent-cloud.net (120.232.24.77)

**Comment by WineChord** [comment]
Please carefully review the following documentation:

* https://go.dev/ref/mod#module-path
* https://go.dev/ref/mod#vcs-find

Note that the module name may not necessarily match the actual code location.
