### ISSUE TITLE
trpc-go doesn't support gRPC protocol?

### ISSUE THREAD

**Issue by zanlichard** [trpc-group/trpc-go#139]
### Preliminary Research

- [ ] I have read the project's documentation.
- [ ] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

**Comment by WineChord** [comment]
https://github.com/trpc-ecosystem/go-codec/tree/main/grpc

**Comment by zanlichard** [comment]
if the protocol config option in trpc_go.yaml config use http and proto definition by protobuf,it means client access server by gRPC?

**Comment by WineChord** [comment]
No, it is actually HTTP-RPC, refer to: https://github.com/trpc-group/trpc-go/tree/main/http

![image](https://github.com/trpc-group/trpc-go/assets/20353612/b61111a6-b0aa-4c48-a030-c256d8753a62)

**Comment by zanlichard** [comment]
if we use  rpc over http, what's the format of the url path client accessing service ?

**Comment by zanlichard** [comment]
trpc-go integrete grpc by codec in trpc-ecosystem,how to modify main.go?
like this  _ "trpc.group/trpc-go/trpc-codec/grpc" in main.go?

**Comment by WineChord** [comment]
> if we use rpc over http, what's the format of the url path client accessing service ?

https://github.com/trpc-group/trpc-go/tree/main/http#custom-url-path

Something like `http://ip:port/trpc.app.server.Greeter/SayHello`.

**Comment by WineChord** [comment]
> trpc-go integrete grpc by codec in trpc-ecosystem,how to modify main.go? like this _ "trpc.group/trpc-go/trpc-codec/grpc" in main.go?

You may check the examples: https://github.com/trpc-ecosystem/go-codec/blob/main/grpc/examples/clients/grpc/main.go

**Comment by zanlichard** [comment]
1. register under base layer
      import  "trpc.group/trpc-go/trpc-go/codec"
      codec.Register("grpc", &serverCodec{}, &clientCodec{})

 2. register implicitly
  add code into main.go as below
  import _ "trpc.group/trpc-go/trpc-codec/grpc"

3. register explicitly
    add code into main.go,as below
    import "trpc.group/trpc-go/trpc-codec/grpc"
    s := trpc.NewServer(server.WithStreamTransport(grpc.DefaultServerStreamTransport))

**Comment by zanlichard** [comment]
what's the difference between gRPC and tgprc?

**Comment by WineChord** [comment]
The tRPC framework itself is an extremely flexible and plugin-based structure. tgrpc is the result of integrating the server/client capabilities of gRPC into the tRPC framework. By using tgrpc, you can leverage various plugin capabilities of tRPC server/client while also interacting with other gRPC server/clients.

**Comment by ninesunqian** [comment]
> No, it is actually HTTP-RPC, refer to: https://github.com/trpc-group/trpc-go/tree/main/http
> 
> ![image](https://private-user-images.githubusercontent.com/20353612/282032984-b61111a6-b0aa-4c48-a030-c256d8753a62.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTg4MTM1OTMsIm5iZiI6MTcxODgxMzI5MywicGF0aCI6Ii8yMDM1MzYxMi8yODIwMzI5ODQtYjYxMTExYTYtYjBhYS00YzQ4LWEwMzAtYzI1NmQ4NzUzYTYyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjE5VDE2MDgxM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlZTQ0OTIzNDk0YTA1YzgyYmQwZmRkZTE2ZDdhMzgzY2JiN2E2ZGJkYmEzMGYyZTQ0NGU1MmEwNWU3Nzk1YTYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.-SoNzSBJYFeQUvUC6G2fmS3VkNQVsA0UU5qloA0Lzaw)

Does the pan-http rpc service support rpc-web client ? for example [nice-rpc-web](https://www.npmjs.com/package/nice-grpc-web)

**Comment by WineChord** [comment]
"pan-http rpc service" is essentially HTTP service, not of trpc/grpc protocols. You may try to use tgrpc server examples: https://github.com/trpc-ecosystem/go-codec/blob/main/grpc/examples/servers/tgrpc/main.go

**Comment by ninesunqian** [comment]
> "pan-http rpc service" is essentially HTTP service, not of trpc/grpc protocols. You may try to use tgrpc server examples: https://github.com/trpc-ecosystem/go-codec/blob/main/grpc/examples/servers/tgrpc/main.go

Does it have js client ？

**Comment by WineChord** [comment]
You can assume it is served as a normal grpc service, any tool that is used to connect to grpc service can be used with it.

**Comment by ninesunqian** [comment]
> You can assume it is served as a normal grpc service, any tool that is used to connect to grpc service can be used with it.

ok. Thank you!
