### ISSUE TITLE
Difference between intranet and open source project

### ISSUE THREAD

**Issue by 44zs44** [trpc-group/trpc-go#152]
I would like to know if there are any key functional differences between the open-source trpc-go and internal network frameworks. For the parts that are not open-sourced, can these tools be replaced with other similar tools?

**Comment by WineChord** [comment]
The two versions are mostly similar, although some deprecated functions have been removed. The trpc-go framework is designed in a plugin-based manner, allowing flexibility in choosing plugin implementations. You have the freedom to utilize any resources available in the [trpc-ecosystem](https://github.com/trpc-ecosystem/) to meet your specific requirements. If certain features are lacking, you can consider developing a new plugin and contributing it to the trpc-ecosystem.

**Comment by 44zs44** [comment]
I am trying to develop REST APIs using the HTTP protocol with the trpc-go framework. In addition to the documentation in the trpc-go/restful directory, when I want to learn about best practices for REST API development, what other content or demos can I try to study?

**Comment by WineChord** [comment]
@44zs44 You may refer to this: https://cloud.google.com/apis/design
