### ISSUE TITLE
Ask some trpc-go project for RESTful API

### ISSUE THREAD

**Issue by 44zs44** [trpc-group/trpc-go#153]
### Question
When I wanted to quickly get started with the trpc-go project to write my own backend project (replacing gin), I found it a bit difficult. I wonder if there are any other relevant excellent code repositories that can provide some writing references. I'm very grateful

**Comment by WineChord** [comment]
Hi, you may read the trpc-cmdline doc here: https://github.com/trpc-group/trpc-cmdline/tree/main/docs/examples/example-2#generating-restful-services
