### ISSUE TITLE
Could you share some of the more frequently asked framework questions from the internal network (similar to common software issues)

### ISSUE THREAD

**Issue by 44zs44** [trpc-group/trpc-go#155]
### Question
When non-Tencent internal learners study the trpc-go framework, they will inevitably encounter some problems. These problems are also likely to be encountered or asked by community learners. These issues can to some extent help community learners better understand the use of this framework and solve some confusing questions.

**Comment by WineChord** [comment]
We do have these documents, and we are considering scheduling it in the future to see how we can handle this task. This is because we need to extract some internal network-related information.

**Comment by Andrew-M-C** [comment]
I have written a series of introductory articles about tRPC. May I ask if the official website allows adding some friendly links to them?

https://cloud.tencent.com/developer/column/4101

I am very glad to contribute to the promotion of tRPC.
