### ISSUE TITLE
Are there community communication channels like WeChat or Slack available for the project?

### ISSUE THREAD

**Issue by iutx** [trpc-group/trpc-go#162]
### Preliminary Research

- [x] I have read the project's documentation.
- [x] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

### Question
None

### Additional Information
None

**Comment by WineChord** [comment]
Duplicate: https://github.com/trpc-group/trpc-go/issues/148

**Comment by iutx** [comment]
> Duplicate: #148

Thanks.
