### ISSUE TITLE
question: how to solve the problem that the program show error code :141 and 171

### ISSUE THREAD

**Issue by jincurry** [trpc-group/trpc-go#165]
### Preliminary Research

- [x] I have read the project's documentation.
- [x] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

### Question
**What's the reason why client side show error code :141, it show the connection is closed, and how to solve the problem?**

When client request server, but the server will spent more than 1 minute to handle some data, the client side will occur error, and the log shows `type:framework, code:141, msg:tcp client transport ReadFrame, cost:49.999809717s, caused by conn is closed` when using tnet, and after change the transport method from tnet to go-net, the error code change to 171, and error message show : `type:framework, code:171, msg:tcp client transport ReadFrame: EOF`

### Additional Information
I will show some code to reappear the question:

client side：
```go
func main() {
	c := pb.NewGreeterClientProxy(client.WithTarget("ip://127.0.0.1:8000"))
	rsp, err := c.Hello(trpc.BackgroundContext(), &pb.HelloRequest{Msg: "world"})
	if err != nil {
		log.Error(err)
		return
	}
	log.Info(rsp.Msg)
}
```
server side:
```go
func main() {
	s := trpc.NewServer()
	pb.RegisterGreeterService(s, &Greeter{})
	if err := s.Serve(); err != nil {
		log.Error(err)
	}
}

type Greeter struct{}

func (g Greeter) Hello(ctx context.Context, req *pb.HelloRequest) (*pb.HelloReply, error) {
	log.Infof("got hello request: %s", req.Msg)
	time.Sleep(1 * time.Minute)
	log.Info("sleep enough time")
	return &pb.HelloReply{Msg: "Hello " + req.Msg + "!"}, nil
}
```

pb file:
```
syntax = "proto3";

package trpc.hello;
option go_package="xagent/cmd/rpc/pb";

service Greeter {
  rpc Hello (HelloRequest) returns (HelloReply) {}
}

message HelloRequest {
  string msg = 1;
}

message HelloReply {
  string msg = 1;
}
```

**Comment by WineChord** [comment]
![image](https://github.com/trpc-group/trpc-go/assets/20353612/90a31c99-a3f3-44d7-977b-e0b2df8c7d4c)

The server has a default idle timeout of 60 seconds. If this timeout is reached without any activity, the server will close the connection. As a result, the client will receive an error stating, "The connection is closed."

**Comment by jincurry** [comment]
Thank you for your reply. I will try adjusting the idle timeout value to test. By the way, if a server is executing a long-duration task, how should I set the timeout and idle timeout? Is there a way to prevent timeouts and keep the connection alive indefinitely?

**Comment by WineChord** [comment]
I've added a section to the doc in https://github.com/trpc-group/trpc-go/pull/166. You can use `idletime: -1` to disable idle timeout:

```yaml
server:
  service:
    - name: trpc.server.service.Method
      network: tcp
      protocol: trpc
      idletime: 60000 # The unit is milliseconds. Setting it to -1 means there is no idle timeout (setting it to 0 will still default to the 60s by the framework)
```

**Comment by jincurry** [comment]
I have noticed your commit, i will set the idle timeout as -1 for test , thanks for your reply again.

**Comment by WineChord** [comment]
"if a server is executing a long-duration task"

Another timeout to be aware of is the service `timeout`. This timeout is embedded in the `ctx context.Context` input argument. However, you must select `ctx.Done()` to catch the context timeout; otherwise, the context timeout will not take effect.

**Comment by jincurry** [comment]
I'm sorry to bother you again. I tested setting the idle time to -1, but the client side did not wait for the server's reply and failed very quickly instead. Is there any suggestion?

there is my `trpc_go.yaml` config for server.
```
server:
  service:
    - name: trpc.hello
      ip: 127.0.0.1
      port: 8000
      idletime: -1
      timeout: 60000
```

and the client and server side output as below:
![image](https://github.com/trpc-group/trpc-go/assets/26199068/962d872d-c2ad-4a3f-b85f-8c7369b1dc9a)
![image](https://github.com/trpc-group/trpc-go/assets/26199068/82695b3c-c2b7-4116-97f3-71558effe2f4)

**Comment by WineChord** [comment]
@jincurry Hi, I found that tnet does not handle negative idle timeout properly. Here is the fix: https://github.com/trpc-group/trpc-go/pull/169/

**Comment by jincurry** [comment]
thanks for your help, I will test later

**Comment by jincurry** [comment]
@WineChord  hi，there has another thing that want you know about the result I test the code.
after I change the server's idletime and timeout as 600000ms， I suppose that the client will get correct result from server, because the server's idletime is longer than the time for handling data. but I still get the same error. `client/main.go:17       type:framework, code:141, msg:tcp client transport ReadFrame, cost:49.999645441s, caused by conn is closed`.

another thing should noticed:
I change the client side code, use `go-net` framework, this time, client got correct response.
client side code:
```
func main() {
	c := pb.NewGreeterClientProxy(client.WithTarget("ip://127.0.0.1:8000"),
		client.WithTransport(transport.GetClientTransport("go-net")))
	rsp, err := c.Hello(trpc.BackgroundContext(), &pb.HelloRequest{Msg: "world"})
	if err != nil {
		log.Error(err)
		return
	}
	log.Info(rsp.Msg)
}
```
![image](https://github.com/trpc-group/trpc-go/assets/26199068/56640435-c180-4e0b-a309-e06345238650)

any suggestion for this?

**Comment by WineChord** [comment]
This is because there is default 50s timeout for client connection pool:

https://github.com/trpc-group/trpc-go/blob/main/docs/user_guide/client/connection_mode.md#connection-pool-1

![image](https://github.com/trpc-group/trpc-go/assets/20353612/87ad6faf-7e3b-4bfa-bca9-c09ca94b0079)

The reason why go-net does not result in an error is because the go-net only check the connection idletimeout when the connection is really idle (in the connection pool's idle list). But tnet do not keep track of this kind of list, the check of idle timeout timer is updated upon very read/write event on the connection no mater the connection is in used or not. In this sense, tnet's connection idle timeout is also acted as read/write timeout.

For tnet client transport, provide additional idle timeout parameter to extend the limit:

```go
import (
	"trpc.group/trpc-go/trpc-go/pool/connpool"
	tnettrans "trpc.group/trpc-go/trpc-go/transport/tnet"
)

func init() {
	tnettrans.DefaultConnPool = connpool.NewConnectionPool(
	      connpool.WithDialFunc(tnettrans.Dial),
	      connpool.WithIdleTimeout(0), // Use 0 to disable the idletimeout for client.
	      connpool.WithHealthChecker(tnettrans.HealthChecker),
      )
}
```

**Comment by jincurry** [comment]
it works. thanks for your reply.

**Comment by WineChord** [comment]
Updated in the doc: https://github.com/trpc-group/trpc-go/pull/170
