### ISSUE TITLE
这个和https://github.com/trpc/trpc 有关系吗？ 如果有的话，未来会实现后端语言到 js 的 End-to-end typesafe 吗？

### ISSUE THREAD

**Issue by adolfheir** [trpc-group/trpc-go#186]
### Preliminary Research

- [ ] I have read the project's documentation.
- [ ] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

**Comment by WineChord** [comment]
1. No.
2. No plans at the moment.

**Comment by adolfheir** [comment]
ok
