### ISSUE TITLE
question: affected/package: 加载trpc_go.yaml如何自定义配置？

### ISSUE THREAD

**Issue by SIN5t** [trpc-group/trpc-go#189]
## 问题描述：将trpc_go.yaml文件放在自定义的目录下，trpc框架应该如何配置，才能扫描到呢？
![image](https://github.com/user-attachments/assets/087b2dbd-5657-49ac-bbea-2a52da31b929)
![image](https://github.com/user-attachments/assets/1a0b27e5-b90a-4335-88a4-7f7adc242cc1)
## 具体:
1. 如果是使用命令行在main中启动服务，个人感觉加一些参数指定就好？但找了下发现不好找
2. 如果想在ide中直接启动，应该如何配置呢？例如goland
![image](https://github.com/user-attachments/assets/71b4842b-cc7b-487e-a42d-9e7302938ac5)

**Comment by WineChord** [comment]
You can modify the global variable https://github.com/trpc-group/trpc-go/blob/1c5c0fbfa33268a4fe00828642d8e586f048eb85/config.go#L41
