### ISSUE TITLE
question: selecctor - How to access HTTPS service not bound at Port 443

### ISSUE THREAD

**Issue by Andrew-M-C** [trpc-group/trpc-go#190]
### Preliminary Research

- [x] I have read the project's documentation.
- [x] I have searched [existing issues](https://github.com/trpc-group/trpc-go/issues) for similar questions to see if my question has already been addressed.

### Question

As I know, trpc provides building selector named `ip`, which also enables dns resolving. Also, it will enable SSL when target port is 443 and protocol is `http`.

However, for certain reason, my HTTP server with SSL is not listening port 443. How can I access this https server NOT listerning Port 443 via trpc?

**Comment by Andrew-M-C** [comment]
I found that I can use 'client.WithReqHead(&thttp.ClientReqHeader{Schema: "https"})' to enable `https`. However, is there any way to enable `https` in config-way?

**Comment by WineChord** [comment]
Refer to README https://github.com/trpc-group/trpc-go/blob/main/http/README.md#configuration-only-1

![image](https://github.com/user-attachments/assets/8d227656-8ced-44c6-ba07-9702a4e58a62)

**Comment by Andrew-M-C** [comment]
So, just making `- ca_cert: "none"` will do, right?
